### ISSUE TITLE
problem with zip-zip-0.3 in installing plugin

### ISSUE THREAD

**Issue by hojjatnikan** [descala/haltr#56]
Hi
i get following error when i want to install plugin :
rake aborted!
NameError: uninitialized constant Zip
/usr/local/rvm/gems/ruby-2.0.0-p598/gems/zip-zip-0.3/lib/zip/zip.rb:3:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.12/lib/bundler/runtime.rb:85:in `require'
/usr/local/rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.12/lib/bundler/runtime.rb:85:in `rescue in block in require'
/usr/local/rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.12/lib/bundler/runtime.rb:68:in `block in require'
/usr/local/rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.12/lib/bundler/runtime.rb:61:in `each'
/usr/local/rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.12/lib/bundler/runtime.rb:61:in `require'
/usr/local/rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.12/lib/bundler.rb:134:in `require'
/var/data/redmine/config/application.rb:7:in `<top (required)>'
/var/data/redmine/Rakefile:5:in `require'
/var/data/redmine/Rakefile:5:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p598/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load'
/usr/local/rvm/gems/ruby-2.0.0-p598/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load_rakefile'
/usr/local/rvm/gems/ruby-2.0.0-p598/gems/rake-10.4.2/lib/rake/application.rb:689:in `raw_load_rakefile'
/usr/local/rvm/gems/ruby-2.0.0-p598/gems/rake-10.4.2/lib/rake/application.rb:94:in `block in load_rakefile'
/usr/local/rvm/gems/ruby-2.0.0-p598/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.0.0-p598/gems/rake-10.4.2/lib/rake/application.rb:93:in `load_rakefile'
/usr/local/rvm/gems/ruby-2.0.0-p598/gems/rake-10.4.2/lib/rake/application.rb:77:in `block in run'
/usr/local/rvm/gems/ruby-2.0.0-p598/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.0.0-p598/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/usr/local/rvm/gems/ruby-2.0.0-p598/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p598/bin/rake:23:in `load'
/usr/local/rvm/gems/ruby-2.0.0-p598/bin/rake:23:in `<main>'
/usr/local/rvm/gems/ruby-2.0.0-p598/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.0.0-p598/bin/ruby_executable_hooks:15:in `<main>'

but when i removed following line from GemFile i don't get any error in installing plugin:
gem "zip"

i think there is conflict in zip version .

Best Regards
Hojjat Nikan

**Comment by hojjatnikan** [comment]
i replaced gem "zip" with gem 'zip-zip' , solved my problem

**Comment by descala** [comment]
What version of Redmine are you using?

**Comment by hojjatnikan** [comment]
Redmine version                2.6.3.stable.13994
Ruby version                   2.0.0-p598 (2014-11-13) [x86_64-linux]
Rails version                  3.2.21
Database adapter               PostgreSQL
